version: '3.8'

services:
  ambev.developerevaluation.webapi:
    container_name: ambev_developer_evaluation_webapi
    build:
      context: .
      dockerfile: src/Ambev.DeveloperEvaluation.WebApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__DefaultConnection=Host=ambev.developerevaluation.database;Port=5432;Database=developer_evaluation;Username=developer;Password=ev@luAt10n
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  ambev.developerevaluation.database:
    container_name: ambev_developer_evaluation_database
    image: postgres:13

    environment:
      POSTGRES_DB: developer_evaluation
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: ev@luAt10n
    ports:
      - "5432:5432"
    restart: unless-stopped

  ambev.developerevaluation.nosql:
    container_name: ambev_developer_evaluation_nosql 
    image: mongo:8.0    
    environment:
        MONGO_INITDB_ROOT_USERNAME: developer
        MONGO_INITDB_ROOT_PASSWORD: ev@luAt10n
    ports:
      - "27017"

  ambev.developerevaluation.cache:
    container_name: ambev_developer_evaluation_cache 
    image: redis:7.4.1-alpine     
    command: redis-server --requirepass ev@luAt10n
    environment:
       MONGO_INITDB_ROOT_USERNAME: developer
       MONGO_INITDB_ROOT_PASSWORD: ev@luAt10n
    ports:
       - "6379"

  # Zookeeper (required for Kafka)
  ambev.developerevaluation.zookeeper:
    image: bitnami/zookeeper:3.9
    container_name: ambev_developer_evaluation_zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  # Kafka Broker
  ambev.developerevaluation.kafka:
    image: bitnami/kafka:3.7
    container_name: ambev_developer_evaluation_kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=ambev.developerevaluation.zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://ambev.developerevaluation.kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - ambev.developerevaluation.zookeeper
  
  # Kafka UI
  ambev.developerevaluation.kafkaui:
    image: provectuslabs/kafka-ui:latest
    container_name: ambev_developer_evaluation_kafkaui
    ports:
      - "8085:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=ambev-cluster
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=ambev.developerevaluation.kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=ambev.developerevaluation.zookeeper:2181
    depends_on:
      - ambev.developerevaluation.kafka